# Generated by Django 4.1.2 on 2022-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in-progress', 'In-Progress'), ('completed', 'Completed')], max_length=100)),
                ('completion_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
