# Generated by Django 4.1.2 on 2022-10-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
